### ISSUE TITLE
Wyciąganie granic gmin / powiatów

### ISSUE THREAD

**Issue by wiktorn** [osm-pl/osm-borders#3]
On 2017-01-05 09:11:18 UTC Władysław Komorek wrote:
> Czy mógłbyś dodać powiaty/województwa z granicami gmin (tylko)?
> Pozwoliłoby to poprawić przebieg granic gmin, wyrysowane dawno temu, ale niedokładnie.

**Comment by WlaKom** [comment]
Można to zrobić z PRG. Podobne bardziej aktualne.
Kiedyś Zbyszek podesłał mi pliki PRG-slaskie.osm.bz2 i PRG-podlaskie.osm.gz na podstawie których aktualizowałem granice gmin które widziałem na http://mapa.abakus.net.pl/.
Może zrobić podobne dla wszystkich województw i umieścić je gdzieś, gotowe do pobrania.

**Comment by wiktorn** [comment]
Mogę pociągnąć granice stąd:
http://www.codgik.gov.pl/index.php/darmowe-dane/prg.html

Ale:
1. nie wygląda na to, by były aktualne (o zmiany wprowadzone od początku 2017 roku)
2. nie wiem, jak wygląda zgodność tych danych z granicami miejscowości

**Comment by wiktorn** [comment]
@WlaKom pobieranie granic jest dostępne pod:
/osm/granice/prg/gminy/<terc>.osm

Działa zarówno dla terc województwa jak i powiatu.

Niestety - na razie tylko gminy, miałem kłopot z odczytaniem plików SHP z powiatami, więc na razie sobie je dopuściłem. Może jak wyjdzie aktualizacja w tym roku, to będzie działać.
