### ISSUE TITLE
Dodanie tagu "boundary=administrative" na liniach

### ISSUE THREAD

**Issue by wiktorn** [osm-pl/osm-borders#4]
On 2017-01-05 09:11:18 UTC Władysław Komorek wrote:
> Czy mógłbyś dodać tag "boundary=administrative", podobnie jak tag "source" przy dodawaniu granic wsi?

**Comment by wiktorn** [comment]
Ok, to dorzucę.

**Comment by WlaKom** [comment]
A czy jest możliwe automatyczne dodawanie Wikidata ID i linku wikipedii dla danej miejscowości/granicy miejscowości?
Na przykład:
wikidata=Q5753514
wikipedia=pl:Zabiele (powiat moniecki)

**Comment by wiktorn** [comment]
Tak, ale to grubsza sprawa. Założyłem na to osobny ticket - #5 

Kłopot z Wikidatą jest taki, że do miejscowości nie są przypisane kody SIMC, co utrudnia wyszukiwanie. Jakby znalazła się dobra dusza, która by je tam uzupełnła, byłoby super :-)
