### ISSUE TITLE
Dorzucenie tagów wikidata oraz wikipedia

### ISSUE THREAD

**Issue by wiktorn** [osm-pl/osm-borders#5]
A czy jest możliwe automatyczne dodawanie Wikidata ID i linku wikipedii dla danej miejscowości/granicy miejscowości?
Na przykład:
wikidata=Q5753514
wikipedia=pl:Zabiele (powiat moniecki)

Można spróbować poprzez:
https://query.wikidata.org/

Wyciągnąć gminę (po TERC), a po tym - miejscowość która tam się znajduje.

**Comment by wiktorn** [comment]
Wypracowałem takie query do Wikidata:
```
SELECT ?miejscowosc ?miejscowoscLabel ?gmina ?terc ?article ?coords
WHERE
{
    ?gmina wdt:P1653 ?terc 
    filter (?terc = '2008032') .
    ?miejscowosc wdt:P131 ?gmina .
    ?article schema:about ?miejscowosc .
    ?article schema:inLanguage "pl" .
    ?miejscowosc  wdt:P625 ?coords
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
  }
```

Które dla danego TERC mam nadzieję, że wyrzuca wikidata / link do wikipedii, dla wszystkich miejscowości w danej gminie (wraz z jakimś punktem dla tej miejscowości)

@WlaKom
Znasz kogoś, kto mógłby to sprawdzić?

**Comment by WlaKom** [comment]
Nie, nie znam nikogo kto mógłby to sprawdzić.

**Comment by wiktorn** [comment]
To dodałem w wersji z delikatnie zmodyfikowanym zapytaniem.

Wydaje się, że zwraca w miarę poprawne informacje, ale jako że w Wikidata punkty dla miejscowości są wprowadzone niezbyt dokladnie (tj. niektóre leżą poza granicami miejscowości), to podchodziłbym do tych danych z pewną rezerwą.

Niemniej - by przypisać tag na podstawie lokalizacji punktu - nazwa z EMUiA musi zawierać się w nazwie z Wikipedii. Mam nadzieję, że to wykluczy większość pomyłek.
