### ISSUE TITLE
dodanie upload='false' do generowanych plików

### ISSUE THREAD

**Issue by zibik** [osm-pl/osm-borders#8]
Jak w temacie - wygenerowane dane nie nadają się do bezpośredniego wysłania, dlatego powinny mieć upload='false' w strukturze XML.

**Comment by wiktorn** [comment]
Nie znam takiego tagu. W którym miejscu miałby się pojawić? Możesz dać jakiś przykład pliku z tym tagiem?

**Comment by zibik** [comment]
To się dodaje zaraz na początku:
`<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' upload='false'>`
